"""increase_image_length

Revision ID: 1d5c06bf91af
Revises: dec6238fdac3
Create Date: 2026-05-05 12:47:05.571713
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = '1d5c06bf91af'
down_revision: Union[str, None] = 'dec6238fdac3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_hotel_feedback_hotel_id', table_name='hotel_feedback')
    op.drop_index('idx_hotel_feedback_user_id', table_name='hotel_feedback')
    op.drop_table('hotel_feedback')
    op.alter_column('package_bookings', 'travelers',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('package_bookings', 'itinerary',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('package_bookings', 'inclusions',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('package_bookings', 'exclusions',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('package_bookings', 'add_ons',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('packages', 'image',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('packages', 'inclusions',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('packages', 'exclusions',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('packages', 'itinerary',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('packages', 'badges',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('packages', 'highlights',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('packages', 'addOns',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('packages', 'policies',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('packages', 'policies',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('packages', 'addOns',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('packages', 'highlights',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('packages', 'badges',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('packages', 'itinerary',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('packages', 'exclusions',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('packages', 'inclusions',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('packages', 'image',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.alter_column('package_bookings', 'add_ons',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('package_bookings', 'exclusions',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('package_bookings', 'inclusions',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('package_bookings', 'itinerary',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('package_bookings', 'travelers',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_table('hotel_feedback',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('user_email', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('hotel_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hotel_name', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('booking_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('check_in', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('check_out', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('overall_score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cleanliness_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('service_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('amenities_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('location_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('value_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('promised_amenities', postgresql.ARRAY(sa.TEXT()), server_default=sa.text("'{}'::text[]"), autoincrement=False, nullable=True),
    sa.Column('delivered_amenities', postgresql.ARRAY(sa.TEXT()), server_default=sa.text("'{}'::text[]"), autoincrement=False, nullable=True),
    sa.Column('missing_amenities', postgresql.ARRAY(sa.TEXT()), server_default=sa.text("'{}'::text[]"), autoincrement=False, nullable=True),
    sa.Column('review_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('pros', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cons', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('would_recommend', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint('amenities_score >= 1 AND amenities_score <= 10', name='hotel_feedback_amenities_score_check'),
    sa.CheckConstraint('cleanliness_score >= 1 AND cleanliness_score <= 10', name='hotel_feedback_cleanliness_score_check'),
    sa.CheckConstraint('location_score >= 1 AND location_score <= 10', name='hotel_feedback_location_score_check'),
    sa.CheckConstraint('overall_score >= 1 AND overall_score <= 10', name='hotel_feedback_overall_score_check'),
    sa.CheckConstraint('service_score >= 1 AND service_score <= 10', name='hotel_feedback_service_score_check'),
    sa.CheckConstraint('value_score >= 1 AND value_score <= 10', name='hotel_feedback_value_score_check'),
    sa.PrimaryKeyConstraint('id', name='hotel_feedback_pkey')
    )
    op.create_index('idx_hotel_feedback_user_id', 'hotel_feedback', ['user_id'], unique=False)
    op.create_index('idx_hotel_feedback_hotel_id', 'hotel_feedback', ['hotel_id'], unique=False)
    # ### end Alembic commands ###
