"""add_hotels_table_and_room_hotel_fk

Revision ID: dec6238fdac3
Revises: 04875eb492e3
Create Date: 2026-05-02 23:26:16.690713
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = 'dec6238fdac3'
down_revision: Union[str, None] = '04875eb492e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('reviews', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('original_price', sa.Float(), nullable=True),
    sa.Column('amenities', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('badges', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('check_in_time', sa.String(length=20), nullable=True),
    sa.Column('check_out_time', sa.String(length=20), nullable=True),
    sa.Column('cancellation_policy', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('hotel_rooms', sa.Column('hotel_id', sa.Integer(), nullable=True))
    op.add_column('hotel_rooms', sa.Column('beds', sa.String(length=100), nullable=True))
    op.add_column('hotel_rooms', sa.Column('size', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_hotel_rooms_hotel_id'), 'hotel_rooms', ['hotel_id'], unique=False)
    op.create_foreign_key(None, 'hotel_rooms', 'hotels', ['hotel_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hotel_rooms', type_='foreignkey')
    op.drop_index(op.f('ix_hotel_rooms_hotel_id'), table_name='hotel_rooms')
    op.drop_column('hotel_rooms', 'size')
    op.drop_column('hotel_rooms', 'beds')
    op.drop_column('hotel_rooms', 'hotel_id')
    op.drop_table('hotels')
    # ### end Alembic commands ###
